services:
  # Backend Service (Node.js)
  - type: web
    name: samayyatra      # Unique name for your backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    branch: main              # Specify the branch if using GitHub or GitLab

  # Frontend Service (React)
  - type: web
    name: samayyatra-1     # Unique name for your frontend
    env: static
    buildCommand: npm run build
    startCommand: serve -s build
    plan: free
    branch: main               # Specify the branch if using GitHub or GitLab
